spring:
  datasource:
    url: jdbc:sqlite:${user.dir}/agent-studio-server/src/main/resources/db/agent-debugger.db
    driver-class-name: org.sqlite.JDBC
    username: 
    password: 

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.sophon.agent.studio.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

logging:
  level:
    com.sophon.agent.studio.mapper: debug

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    groups-order: asc