CREATE TABLE `sophon_agent_model_config` (
      `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'primary_id',
      `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
      `modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'update time',
      `name` varchar(128)  NOT NULL DEFAULT '' COMMENT '用户自定义名称',
      `description` varchar(512)  NOT NULL DEFAULT '' COMMENT '模型描述',
      `model_url` varchar(1000)  NOT NULL DEFAULT '' COMMENT '接入模型的基础地址',
      `model_key` varchar(1000)  NOT NULL DEFAULT '' COMMENT '接入模型的api-key',
      `model_name` varchar(1000)  NOT NULL DEFAULT '' COMMENT '对应接入方模型名称',
      `config` longtext  COMMENT '模型配置其他扩展信息,如接入模型方类型,方舟、百炼等',
      `is_delete` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除，0否，1是',
      `modify_user` varchar(128)  DEFAULT NULL COMMENT '修改人',
      `create_user` varchar(128)  DEFAULT NULL COMMENT '创建人',
      `modalities` varchar(1024) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '模态支持',
      `max_completion_token_limit` int DEFAULT NULL COMMENT '模型最大输出token长度',
      `model_app_tag` varchar(256) COLLATE utf8mb4_general_ci DEFAULT '[]' COMMENT '模型应用标签',
      `default_params` varchar(512) COLLATE utf8mb4_general_ci DEFAULT '{}' COMMENT '默认参数',
      `support_stream` tinyint(1) DEFAULT '1' COMMENT '是否支持stream',
      `support_system` tinyint(1) DEFAULT '1' COMMENT '是否支持system指令',
      `support_reasoning` tinyint(1) DEFAULT '0' COMMENT '是否兼容思维链标准协议',
      `timeout_seconds` int DEFAULT NULL COMMENT '超时时间',
      PRIMARY KEY (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='模型配置信息表'